info:
  description: API definition for Quiz Master web application.
  title: Quiz Master API
  version: 1.0.0
openapi: 3.0.0
paths:
  /chapters/{chapter_id}/quizzes:
    post:
      parameters:
      - in: path
        name: chapter_id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                date_of_quiz:
                  format: date-time
                  type: string
                duration:
                  type: integer
                remarks:
                  type: string
              required:
              - date_of_quiz
              - duration
              type: object
      responses:
        '201':
          description: Quiz created
      summary: Create a new quiz in a chapter
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              type: object
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
      summary: Login user
  /quiz/{quiz_id}/submit:
    post:
      parameters:
      - in: path
        name: quiz_id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                answers:
                  items:
                    properties:
                      question_id:
                        type: integer
                      selected_option:
                        type: integer
                    required:
                    - question_id
                    - selected_option
                    type: object
                  type: array
              required:
              - answers
              type: object
      responses:
        '200':
          description: Quiz submitted and score recorded
      summary: Submit answers for a quiz
  /quizzes/{quiz_id}/questions:
    get:
      parameters:
      - in: path
        name: quiz_id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: List of questions
      summary: Get questions for a quiz
    post:
      parameters:
      - in: path
        name: quiz_id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                correct_option:
                  type: integer
                option_1:
                  type: string
                option_2:
                  type: string
                option_3:
                  type: string
                option_4:
                  type: string
                question_text:
                  type: string
              required:
              - question_text
              - option_1
              - option_2
              - option_3
              - option_4
              - correct_option
              type: object
      responses:
        '201':
          description: Question added
      summary: Add a question to a quiz
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                date_of_birth:
                  format: date
                  type: string
                email:
                  type: string
                full_name:
                  type: string
                password:
                  type: string
                qualification:
                  type: string
              required:
              - email
              - password
              - full_name
              type: object
      responses:
        '201':
          description: User registered
        '400':
          description: User already exists
      summary: Register new user
  /scores:
    get:
      responses:
        '200':
          description: List of scores
      summary: Get current user scores
  /subjects:
    get:
      responses:
        '200':
          description: List of subjects
      summary: List all subjects
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
      responses:
        '201':
          description: Subject created
      summary: Create a new subject
  /subjects/{subject_id}/chapters:
    post:
      parameters:
      - in: path
        name: subject_id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
      responses:
        '201':
          description: Chapter created
      summary: Add a chapter to a subject
